#! /bin/bash

BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ "$BRANCH" == "prod" ]]; then
  if [[ `git status --porcelain` ]]; then
    echo 'ERROR! Aborting script.';
    echo '===> Local branch and upstream prod are not equal';
    exit 1;
  else
    echo 'Starting generation and deployment to PROD stage from prod branch';
    echo 'Starting deploy to PROD Stage ...';
    echo '===> prod branch';

    mv ./public/config.js ./public/config.js.dis
    mv ./public/config_example.js ./public/config.js

    echo 'Use example_config.js as config ...';
    echo '===> example config renamed and used as deployed config';

    npm run build && ./vendor/bin/dep deploy prod
    mv ./public/config.js ./public/config_example.js
    mv ./public/config.js.dis ./public/config.js
  fi
fi
